Competed the footer section markup
AlexMoskalyk/bc-project pull request #16
Opened 2021-07-24 12:12 UTC by frandrew90

Update footer.html

2021-07-24 17:35 UTC, AlexMoskalyk requested changes

2021-07-24 17:35 UTC, AlexMoskalyk commented on src/partials/footer.html
> +        <p class="footer-text">homemade ice cream made</p>
Я считаю что это заголовок h2 в котором есть span для стилизации текста

2021-07-24 17:35 UTC, AlexMoskalyk commented on src/partials/footer.html
> +        <p class="footer-text">homemade ice cream made</p>
span для строки 7

2021-07-24 17:43 UTC, frandrew90 commented on src/partials/footer.html
> +        <p class="footer-text">homemade ice cream made</p>
Андрей говорил, что в футере заголовков быть не может.

2021-07-24 18:10 UTC, frandrew90 commented on src/partials/footer.html
> +        <p class="footer-text">homemade ice cream made</p>
Отредактировал, через <p> и <span>

2021-07-25 13:44 UTC, AlexMoskalyk approved these changes

2021-07-25 13:44 UTC, merged