products section html markup
AlexMoskalyk/bc-project pull request #17
Opened 2021-07-24 13:10 UTC by ViacheslavKozlov

2021-07-24 16:42 UTC, AlexMoskalyk requested changes

2021-07-24 16:42 UTC, AlexMoskalyk commented on src/partials/products.html
> +<section class="container">
для контейнера сделать отдельный div, прописать класы

2021-07-24 20:05 UTC, ViacheslavKozlov commented on src/partials/products.html
> +<section class="container">
добавил div для container
добавил классы
закомментировал "точки" до уточнения с Андреем как их делать

2021-07-25 12:11 UTC, AlexMoskalyk approved these changes

2021-07-25 12:11 UTC, AlexMoskalyk commented on src/partials/products.html
> +<section>
Добавить класс секции, в следующей ветке,

2021-07-25 12:11 UTC, merged